### ISSUE TITLE
[Docs] How to setup

### ISSUE THREAD

**Issue by 4censord** [bitwave-tv/bitwave-media-server#316]
Please document how to run this yourself.

From what i could figure out this requires Google firebase access.  
* Is there a way to run this in a dev setting without firebase?
* How does one setup a connection to firebase?

**Comment by BHTech2024** [comment]
The author is totally unpleasant and uncultured, so you can count this project as a dead spot.

**Comment by 4censord** [comment]
Ah, i totally forgot i opened this. 
The problem I had been trying to solve has been solved (by using something different) for years now.
